/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class Chapters {
    private String ChapterName;
    private String TotalTopics;
    private String TimeTaken;
    private int TotalTestedMarks;
    private String idCourseSubject;
    private String idCourseSubjectChapter;
    private int EarnedMarks;
    private int PendingExerciseTopics;
    private int CompletedTopics;
    private int ScoreRed;
    private int TimeSpent;
    private int PassedComplexity;
    private int ScoreAmber;
    private int NotesCount;

    public void setChapterName(String chapterName) {
        this.ChapterName = chapterName;
    }

    public String getChapterName() {
        return ChapterName;
    }

    public int getPendingExerciseTopics() {
        return PendingExerciseTopics;
    }

    public void setPendingExerciseTopics(int pendingExerciseTopics) {
        PendingExerciseTopics = pendingExerciseTopics;
    }

    public void setTotalTopics(String totalTopics) {
        this.TotalTopics = totalTopics;
    }

    public String getTotalTopics() {
        return TotalTopics;
    }


    public void setTimeTaken(String timeTaken) {
        this.TimeTaken = timeTaken;
    }

    public String getTimeTaken() {
        return TimeTaken;
    }


    public void setTotalTestedMarks(int totalTestedMarks) {
        this.TotalTestedMarks = totalTestedMarks;
    }

    public int getTotalTestedMarks() {
        return TotalTestedMarks;
    }


    public void setIdCourseSubject(String idCourseSubject) {
        this.idCourseSubject = idCourseSubject;
    }

    public String getIdCourseSubject() {
        return idCourseSubject;
    }


    public void setIdCourseSubjectChapter(String idCourseSubjectChapter) {
        this.idCourseSubjectChapter = idCourseSubjectChapter;
    }

    public String getIdCourseSubjectChapter() {
        return idCourseSubjectChapter;
    }


    public void setEarnedMarks(int earnedMarks) {
        this.EarnedMarks = earnedMarks;
    }

    public int getEarnedMarks() {
        return EarnedMarks;
    }

    public int getCompletedTopics() {
        return CompletedTopics;
    }

    public void setCompletedTopics(int completedTopics) {
        CompletedTopics = completedTopics;
    }

    public int getScoreRed() {
        return ScoreRed;
    }

    public void setScoreRed(int scoreRed) {
        ScoreRed = scoreRed;
    }

    public int getTimeSpent() {
        return TimeSpent;
    }

    public void setTimeSpent(int timeSpent) {
        TimeSpent = timeSpent;
    }

    public int getPassedComplexity() {
        return PassedComplexity;
    }

    public void setPassedComplexity(int passedComplexity) {
        PassedComplexity = passedComplexity;
    }

    public int getScoreAmber() {
        return ScoreAmber;
    }

    public void setScoreAmber(int scoreAmber) {
        ScoreAmber = scoreAmber;
    }

    public int getNotesCount() {
        return NotesCount;
    }

    public void setNotesCount(int notesCount) {
        NotesCount = notesCount;
    }
}