/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class NotesCount {
    private String chaptername;
    private String subjectname;
    private String idcoursesubject;
    private String idcoursesubjectchapter;
    private String notescount;

    public void setChaptername(String chaptername) {
        this.chaptername = chaptername;
    }

    public String getChaptername() {
        return chaptername;
    }


    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }

    public String getSubjectname() {
        return subjectname;
    }


    public void setIdcoursesubject(String idcoursesubject) {
        this.idcoursesubject = idcoursesubject;
    }

    public String getIdcoursesubject() {
        return idcoursesubject;
    }


    public void setIdcoursesubjectchapter(String idcoursesubjectchapter) {
        this.idcoursesubjectchapter = idcoursesubjectchapter;
    }

    public String getIdcoursesubjectchapter() {
        return idcoursesubjectchapter;
    }


    public void setNotescount(String notescount) {
        this.notescount = notescount;
    }

    public String getNotescount() {
        return notescount;
    }

}