/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class PassedComplexity {
    private String ChapterName;
    private String SubjectName;
    private String idCourseSubject;
    private String idCourseSubjectChapter;
    private String PassedComplexity;

    public void setChapterName(String chapterName) {
        this.ChapterName = chapterName;
    }

    public String getChapterName() {
        return ChapterName;
    }


    public void setSubjectName(String subjectName) {
        this.SubjectName = subjectName;
    }

    public String getSubjectName() {
        return SubjectName;
    }


    public void setIdCourseSubject(String idCourseSubject) {
        this.idCourseSubject = idCourseSubject;
    }

    public String getIdCourseSubject() {
        return idCourseSubject;
    }


    public void setIdCourseSubjectChapter(String idCourseSubjectChapter) {
        this.idCourseSubjectChapter = idCourseSubjectChapter;
    }

    public String getIdCourseSubjectChapter() {
        return idCourseSubjectChapter;
    }


    public void setPassedComplexity(String passedComplexity) {
        this.PassedComplexity = passedComplexity;
    }

    public String getPassedComplexity() {
        return PassedComplexity;
    }

}