/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class PassedComplexity {
    private String chaptername;
    private String subjectname;
    private String idcoursesubject;
    private String idcoursesubjectchapter;
    private String passedcomplexity;

    public void setChaptername(String chaptername) {
        this.chaptername = chaptername;
    }

    public String getChaptername() {
        return chaptername;
    }


    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }

    public String getSubjectname() {
        return subjectname;
    }


    public void setIdcoursesubject(String idcoursesubject) {
        this.idcoursesubject = idcoursesubject;
    }

    public String getIdcoursesubject() {
        return idcoursesubject;
    }


    public void setIdcoursesubjectchapter(String idcoursesubjectchapter) {
        this.idcoursesubjectchapter = idcoursesubjectchapter;
    }

    public String getIdcoursesubjectchapter() {
        return idcoursesubjectchapter;
    }


    public void setPassedcomplexity(String passedcomplexity) {
        this.passedcomplexity = passedcomplexity;
    }

    public String getPassedcomplexity() {
        return passedcomplexity;
    }

}