/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class Scores {
    private String ChapterName;
    private String TotalTopics;
    private String TimeTaken;
    private String SubjectName;
    private String TotalTestedMarks;
    private String idCourseSubject;
    private String idCourseSubjectChapter;
    private String EarnedMarks;
    

    public void setChapterName(String chapterName) {
        this.ChapterName = chapterName;
    }

    public String getChapterName() {
        return ChapterName;
    }


    public void setTotalTopics(String totalTopics) {
        this.TotalTopics = totalTopics;
    }

    public String getTotalTopics() {
        return TotalTopics;
    }


    public void setTimeTaken(String timeTaken) {
        this.TimeTaken = timeTaken;
    }

    public String getTimeTaken() {
        return TimeTaken;
    }


    public void setSubjectname(String subjectname) {
        this.SubjectName = subjectname;
    }

    public String getSubjectname() {
        return SubjectName;
    }


    public void setTotalTestedMarks(String totalTestedMarks) {
        this.TotalTestedMarks = totalTestedMarks;
    }

    public String getTotalTestedMarks() {
        return TotalTestedMarks;
    }


    public void setIdCourseSubject(String idCourseSubject) {
        this.idCourseSubject = idCourseSubject;
    }

    public String getIdCourseSubject() {
        return idCourseSubject;
    }


    public void setIdCourseSubjectChapter(String idCourseSubjectChapter) {
        this.idCourseSubjectChapter = idCourseSubjectChapter;
    }

    public String getIdCourseSubjectChapter() {
        return idCourseSubjectChapter;
    }


    public void setEarnedMarks(String earnedMarks) {
        this.EarnedMarks = earnedMarks;
    }

    public String getEarnedMarks() {
        return EarnedMarks;
    }

}