/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class ScoreThreshold {
    private String chaptername;
    private String scoreamber;
    private String scorered;
    private String subjectname;
    private String idcoursesubject;
    private String idcoursesubjectchapter;

    public void setChaptername(String chaptername) {
        this.chaptername = chaptername;
    }

    public String getChaptername() {
        return chaptername;
    }


    public void setScoreamber(String scoreamber) {
        this.scoreamber = scoreamber;
    }

    public String getScoreamber() {
        return scoreamber;
    }


    public void setScorered(String scorered) {
        this.scorered = scorered;
    }

    public String getScorered() {
        return scorered;
    }


    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }

    public String getSubjectname() {
        return subjectname;
    }


    public void setIdcoursesubject(String idcoursesubject) {
        this.idcoursesubject = idcoursesubject;
    }

    public String getIdcoursesubject() {
        return idcoursesubject;
    }


    public void setIdcoursesubjectchapter(String idcoursesubjectchapter) {
        this.idcoursesubjectchapter = idcoursesubjectchapter;
    }

    public String getIdcoursesubjectchapter() {
        return idcoursesubjectchapter;
    }

}