/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class Scores {
    private String chaptername;
    private String totaltopics;
    private String timetaken;
    private String subjectname;
    private String totaltestedmarks;
    private String idcoursesubject;
    private String idcoursesubjectchapter;
    private String earnedmarks;

    public void setChaptername(String chaptername) {
        this.chaptername = chaptername;
    }

    public String getChaptername() {
        return chaptername;
    }


    public void setTotaltopics(String totaltopics) {
        this.totaltopics = totaltopics;
    }

    public String getTotaltopics() {
        return totaltopics;
    }


    public void setTimetaken(String timetaken) {
        this.timetaken = timetaken;
    }

    public String getTimetaken() {
        return timetaken;
    }


    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }

    public String getSubjectname() {
        return subjectname;
    }


    public void setTotaltestedmarks(String totaltestedmarks) {
        this.totaltestedmarks = totaltestedmarks;
    }

    public String getTotaltestedmarks() {
        return totaltestedmarks;
    }


    public void setIdcoursesubject(String idcoursesubject) {
        this.idcoursesubject = idcoursesubject;
    }

    public String getIdcoursesubject() {
        return idcoursesubject;
    }


    public void setIdcoursesubjectchapter(String idcoursesubjectchapter) {
        this.idcoursesubjectchapter = idcoursesubjectchapter;
    }

    public String getIdcoursesubjectchapter() {
        return idcoursesubjectchapter;
    }


    public void setEarnedmarks(String earnedmarks) {
        this.earnedmarks = earnedmarks;
    }

    public String getEarnedmarks() {
        return earnedmarks;
    }

}