/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class ScoreThreshold {
    private String ChapterName;
    private String ScoreAmber;
    private String ScoreRed;
    private String SubjectName;
    private String idCourseSubject;
    private String idCourseSubjectChapter;

    public void setChapterName(String chapterName) {
        this.ChapterName = chapterName;
    }

    public String getChapterName() {
        return ChapterName;
    }


    public void setScoreAmber(String scoreAmber) {
        this.ScoreAmber = scoreAmber;
    }

    public String getScoreAmber() {
        return ScoreAmber;
    }


    public void setScoreRed(String scoreRed) {
        this.ScoreRed = scoreRed;
    }

    public String getScoreRed() {
        return ScoreRed;
    }


    public void setSubjectName(String subjectName) {
        this.SubjectName = subjectName;
    }

    public String getSubjectName() {
        return SubjectName;
    }


    public void setIdCourseSubject(String idCourseSubject) {
        this.idCourseSubject = idCourseSubject;
    }

    public String getIdCourseSubject() {
        return idCourseSubject;
    }


    public void setIdCourseSubjectChapter(String idCourseSubjectChapter) {
        this.idCourseSubjectChapter = idCourseSubjectChapter;
    }

    public String getIdCourseSubjectChapter() {
        return idCourseSubjectChapter;
    }

}