/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

public class StudyCenter {
    private Scores[] scores;
    private NotesCount[] notescount;
    private ScoreThreshold[] scorethreshold;
    private CompletionStatus[] completionstatus;
    private PassedComplexity[] passedcomplexity;

    public void setScores(Scores[] scores) {
        this.scores = scores;
    }

    public Scores[] getScores() {
        return scores;
    }


    public void setNotescount(NotesCount[] notescount) {
        this.notescount = notescount;
    }

    public NotesCount[] getNotescount() {
        return notescount;
    }


    public void setScorethreshold(ScoreThreshold[] scorethreshold) {
        this.scorethreshold = scorethreshold;
    }

    public ScoreThreshold[] getScorethreshold() {
        return scorethreshold;
    }


    public void setCompletionstatus(CompletionStatus[] completionstatus) {
        this.completionstatus = completionstatus;
    }

    public CompletionStatus[] getCompletionstatus() {
        return completionstatus;
    }


    public void setPassedcomplexity(PassedComplexity[] passedcomplexity) {
        this.passedcomplexity = passedcomplexity;
    }

    public PassedComplexity[] getPassedcomplexity() {
        return passedcomplexity;
    }

}