/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.education.corsalite.models.responsemodels;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class StudyCenter {
    private ArrayList<Scores> Scores;
    private ArrayList<NotesCount> NotesCount;
    private ArrayList<ScoreThreshold> ScoreThreshold;
    private ArrayList<CompletionStatus> CompletionStatus;
    private ArrayList<PassedComplexity> PassedComplexity;
    public HashMap<String, List<CompletionStatus>> tilesMap;

    public void setScores(ArrayList<Scores> scores) {
        this.Scores = scores;
    }

    public ArrayList<Scores> getScores() {
        return Scores;
    }


    public void setNotesCount(ArrayList<NotesCount> notesCount) {
        this.NotesCount = notesCount;
    }

    public ArrayList<NotesCount> getNotesCount() {
        return NotesCount;
    }


    public void setScoreThreshold(ArrayList<ScoreThreshold> scoreThreshold) {
        this.ScoreThreshold = scoreThreshold;
    }

    public ArrayList<ScoreThreshold> getScoreThreshold() {
        return ScoreThreshold;
    }


    public void setCompletionStatus(ArrayList<CompletionStatus> completionStatus) {
        this.CompletionStatus = completionStatus;
    }

    public ArrayList<CompletionStatus> getCompletionStatus() {
        return CompletionStatus;
    }


    public void setPassedComplexity(ArrayList<PassedComplexity> passedComplexity) {
        this.PassedComplexity = passedComplexity;
    }

    public ArrayList<PassedComplexity> getPassedComplexity() {
        return PassedComplexity;
    }

}