/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.corsalite.tabletapp.models.responsemodels;

public class NotesCount {
    private String ChapterName;
    private String SubjectName;
    private String idCourseSubject;
    private String idCourseSubjectChapter;
    private String NotesCount;

    public void setChapterName(String chapterName) {
        this.ChapterName = chapterName;
    }

    public String getChapterName() {
        return ChapterName;
    }


    public void setSubjectName(String subjectName) {
        this.SubjectName = subjectName;
    }

    public String getSubjectName() {
        return SubjectName;
    }


    public void setIdCourseSubject(String idCourseSubject) {
        this.idCourseSubject = idCourseSubject;
    }

    public String getIdCourseSubject() {
        return idCourseSubject;
    }


    public void setIdCourseSubjectChapter(String idCourseSubjectChapter) {
        this.idCourseSubjectChapter = idCourseSubjectChapter;
    }

    public String getIdCourseSubjectChapter() {
        return idCourseSubjectChapter;
    }


    public void setNotesCount(String notesCount) {
        this.NotesCount = notesCount;
    }

    public String getNotesCount() {
        return NotesCount;
    }

}